spring.application.name=StudyManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/studymanagement
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=91ee9c4b064ee49b252abaf692bdf28166257b193b3125556f025ab5e053e901
# Thời gian sống của Token 24h
jwt.expiration-ms=86400000
