package com.se191116.studymanagement.model.entity;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    ASSIGNMENT_CREATED,
    WEEKLY_REPORT_SUBMITTED,
    WEEKLY_REPORT_REVIEWED,
    WEEKLY_REPORT_DUE_SOON,
    WEEKLY_REPORT_OVERDUE,
    ASSESSMENT_ROUND_STARTED,
    ASSESSMENT_SCORE_SUBMITTED,
    ASSESSMENT_RESULT_PUBLISHED
}
