package com.se191116.studymanagement.model.entity;

public enum NotificationType {
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    ASSIGNMENT_CREATED,
    WEEKLY_REPORT_SUBMITTED,
    WEEKLY_REPORT_REVIEWED,
    WEEKLY_REPORT_DUE_SOON,
    WEEKLY_REPORT_OVERDUE,
    ASSESSMENT_ROUND_STARTED,
    ASSESSMENT_SCORE_SUBMITTED,
    ASSESSMENT_RESULT_PUBLISHED,
    GROUP_TASK_CREATED,
    GROUP_TASK_DUE_SOON,
    GROUP_TASK_OVERDUE,
    GROUP_SUBMISSION_CREATED,
    GROUP_SUBMISSION_REVIEWED,
    GROUP_MEMBER_ROLE_UPDATED,
    GROUP_MEMBER_MUTED,
    GROUP_MEMBER_REMOVED
}
